const TASK_NAME = 'Task Name';
const WBS_CODE_PPSA = 'WBS Code (PPSA)';
const ROLE_NAME_PRICING_SHEET =
  'Role Name (Pricing Sheet Original Reference - Do n';
const ASSIGNED_TO = 'Assigned To';
const BUDGETED_HOURS = 'Budgeted Hours';
const EFFORT_HRS = 'Effort (hrs)';
const WORKED_TASK_HOURS = 'Worked Task Hours';
const REMAINING_TASK_HOURS = 'Remaining Task Hours';
const DURATION = 'Duration';
const START_DATE = 'Start Date';
const END_DATE = 'End Date';
const PREDECESSORS = 'Predecessors';
const PERCENT_ALLOCATION = '% Allocation';
const TASK_TYPE = 'Task Type';
const COMMENTS = 'Comments';
const OPEN_FOR_TIME = 'Open for Time';
const WORKED_MINUTES_PPSA = 'Worked Minutes (PPSA)';
const REMAINING_MINUTES_PPSA = 'Remaining Minutes (PPSA)';

// An array, to guarantee order
export const columnMapping = [
  TASK_NAME,
  WBS_CODE_PPSA,
  ROLE_NAME_PRICING_SHEET,
  ASSIGNED_TO,
  BUDGETED_HOURS,
  EFFORT_HRS,
  WORKED_TASK_HOURS,
  REMAINING_TASK_HOURS,
  DURATION,
  START_DATE,
  END_DATE,
  PREDECESSORS,
  PERCENT_ALLOCATION,
  TASK_TYPE,
  COMMENTS,
  OPEN_FOR_TIME,
  WORKED_MINUTES_PPSA,
  REMAINING_MINUTES_PPSA,
];

export const tree = [
  {
    [TASK_NAME]: 'P0 (Phase 0)',
    [WBS_CODE_PPSA]: '1',
    [ROLE_NAME_PRICING_SHEET]: '',
    [ASSIGNED_TO]: '',
    [BUDGETED_HOURS]: 618,
    [EFFORT_HRS]: 618,
    [WORKED_TASK_HOURS]: 0,
    [REMAINING_TASK_HOURS]: 618,
    [DURATION]: '68d',
    [START_DATE]: '08/24/25',
    [END_DATE]: '11/26/25',
    [PREDECESSORS]: '',
    [PERCENT_ALLOCATION]: '',
    [TASK_TYPE]: '',
    [COMMENTS]: '',
    [OPEN_FOR_TIME]: 1,
    [WORKED_MINUTES_PPSA]: 0,
    [REMAINING_MINUTES_PPSA]: 37080,
    children: [
      {
        [TASK_NAME]: 'P0-Delivery / Project Management',
        [WBS_CODE_PPSA]: '1.1',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 118,
        [EFFORT_HRS]: 118,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 118,
        [DURATION]: '68d',
        [START_DATE]: '08/24/25',
        [END_DATE]: '11/26/25',
        [PREDECESSORS]: '',
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: '',
        [OPEN_FOR_TIME]: 1,
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 7080,
        children: [
          {
            [TASK_NAME]: 'Phase 0 Day Before',
            [WBS_CODE_PPSA]: '1.1.1',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '1d',
            [START_DATE]: '08/24/25',
            [END_DATE]: '08/24/25',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: 'PM-USA-P0-1',
            [WBS_CODE_PPSA]: '1.1.2',
            [ROLE_NAME_PRICING_SHEET]: '(US Project Manager-P0-1)',
            [ASSIGNED_TO]: '(Project Manager - Lead 1)',
            [BUDGETED_HOURS]: 118,
            [EFFORT_HRS]: 118,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 118,
            [DURATION]: '67d',
            [START_DATE]: '08/25/25',
            [END_DATE]: '11/26/25',
            [PREDECESSORS]: 3,
            [PERCENT_ALLOCATION]: 0.220149253731343,
            [TASK_TYPE]: 'P0-PM Only',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: 1,
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 7080,
            children: [],
          },
          {
            [TASK_NAME]: '39 - Recruiting  / ONB - Advisory Services',
            [WBS_CODE_PPSA]: '1.1.3',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '19d',
            [START_DATE]: '08/25/25',
            [END_DATE]: '09/19/25',
            [PREDECESSORS]: 3,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: 1,
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: '40 - Core - Advisory Services',
            [WBS_CODE_PPSA]: '1.1.4',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '9d',
            [START_DATE]: '08/25/25',
            [END_DATE]: '09/05/25',
            [PREDECESSORS]: 3,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: '41 - Talent - Advisory Services',
            [WBS_CODE_PPSA]: '1.1.5',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '19d',
            [START_DATE]: '08/25/25',
            [END_DATE]: '09/19/25',
            [PREDECESSORS]: 3,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: 1,
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P0-39 - Recruiting  / ONB - Advisory Services',
        [WBS_CODE_PPSA]: '1.2',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 150,
        [EFFORT_HRS]: 150,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 150,
        [DURATION]: '48d',
        [START_DATE]: '09/22/25',
        [END_DATE]: '11/26/25',
        [PREDECESSORS]: 5,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 39,
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 9000,
        children: [
          {
            [TASK_NAME]: 'Phase 0 Advisory-Rec',
            [WBS_CODE_PPSA]: '1.2.1',
            [ROLE_NAME_PRICING_SHEET]:
              '(39-Rec/Onb Advisory-Phase 0 Advisory-Rec-Lead-USA-P0-1)',
            [ASSIGNED_TO]: '(Recruiting / ONB - Advisory Services - Lead 1)',
            [BUDGETED_HOURS]: 150,
            [EFFORT_HRS]: 150,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 150,
            [DURATION]: '48d',
            [START_DATE]: '09/22/25',
            [END_DATE]: '11/26/25',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.390625,
            [TASK_TYPE]: 'P0-Recruiting  / ONB - Advisory Services',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 9000,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P0-40 - Core - Advisory Services',
        [WBS_CODE_PPSA]: '1.3',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 200,
        [EFFORT_HRS]: 200,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 200,
        [DURATION]: '40d',
        [START_DATE]: '09/08/25',
        [END_DATE]: '10/31/25',
        [PREDECESSORS]: 6,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 40,
        [OPEN_FOR_TIME]: 1,
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 12000,
        children: [
          {
            [TASK_NAME]: 'Phase 0 Advisory -EC',
            [WBS_CODE_PPSA]: '1.3.1',
            [ROLE_NAME_PRICING_SHEET]:
              '(40-Core Advisory-Phase 0 Advisory -EC-Lead-USA-P0-1)',
            [ASSIGNED_TO]: '(Core - Advisory Services - Lead 1)',
            [BUDGETED_HOURS]: 200,
            [EFFORT_HRS]: 200,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 200,
            [DURATION]: '40d',
            [START_DATE]: '09/08/25',
            [END_DATE]: '10/31/25',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.625,
            [TASK_TYPE]: 'P0-Core - Advisory Services',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: 1,
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 12000,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P0-41 - Talent - Advisory Services',
        [WBS_CODE_PPSA]: '1.4',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 150,
        [EFFORT_HRS]: 150,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 150,
        [DURATION]: '48d',
        [START_DATE]: '09/22/25',
        [END_DATE]: '11/26/25',
        [PREDECESSORS]: 7,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 41,
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 9000,
        children: [
          {
            [TASK_NAME]: 'Phase 0 Advisory-Talent',
            [WBS_CODE_PPSA]: '1.4.1',
            [ROLE_NAME_PRICING_SHEET]:
              '(31-Talent Advisory-Phase 0 Advisory-Talent-Lead-USA-P0-1)',
            [ASSIGNED_TO]: '(Talent - Advisory Services - Lead 1)',
            [BUDGETED_HOURS]: 150,
            [EFFORT_HRS]: 150,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 150,
            [DURATION]: '48d',
            [START_DATE]: '09/22/25',
            [END_DATE]: '11/26/25',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.390625,
            [TASK_TYPE]: 'P0-Talent - Advisory Services',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 9000,
            children: [],
          },
        ],
      },
    ],
  },
  {
    [TASK_NAME]: 'P1 (Phase 1)',
    [WBS_CODE_PPSA]: '2',
    [ROLE_NAME_PRICING_SHEET]: '',
    [ASSIGNED_TO]: '',
    [BUDGETED_HOURS]: 5250,
    [EFFORT_HRS]: 5250,
    [WORKED_TASK_HOURS]: 0,
    [REMAINING_TASK_HOURS]: 5750,
    [DURATION]: '452d',
    [START_DATE]: '12/07/25',
    [END_DATE]: '09/20/27',
    [PREDECESSORS]: '',
    [PERCENT_ALLOCATION]: '',
    [TASK_TYPE]: '',
    [COMMENTS]: '',
    [OPEN_FOR_TIME]: '',
    [WORKED_MINUTES_PPSA]: 0,
    [REMAINING_MINUTES_PPSA]: 345000,
    children: [
      {
        [TASK_NAME]: 'P1-Delivery / Project Management',
        [WBS_CODE_PPSA]: '2.1',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 1175,
        [EFFORT_HRS]: 1175,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 1275,
        [DURATION]: '190d',
        [START_DATE]: '12/07/25',
        [END_DATE]: '09/04/26',
        [PREDECESSORS]: '',
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: '',
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 76500,
        children: [
          {
            [TASK_NAME]: 'Phase 1 Day Before',
            [WBS_CODE_PPSA]: '2.1.1',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '1d',
            [START_DATE]: '12/07/25',
            [END_DATE]: '12/07/25',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: 'PM-USA-P1-1',
            [WBS_CODE_PPSA]: '2.1.2',
            [ROLE_NAME_PRICING_SHEET]: '(US Project Manager-P1-1)',
            [ASSIGNED_TO]: '(Project Manager - Lead 11)',
            [BUDGETED_HOURS]: 450,
            [EFFORT_HRS]: 550,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 550,
            [DURATION]: '189d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '09/04/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: 0.363756613756614,
            [TASK_TYPE]: 'P1-PM / DM / PC',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 33000,
            children: [],
          },
          {
            [TASK_NAME]: 'DM-LATAM-P1-2',
            [WBS_CODE_PPSA]: '2.1.3',
            [ROLE_NAME_PRICING_SHEET]: '(LATAM Delivery Manager-P1-2)',
            [ASSIGNED_TO]: '(LATAM - Delivery Manager - Lead 12)',
            [BUDGETED_HOURS]: 450,
            [EFFORT_HRS]: 375,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 375,
            [DURATION]: '189d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '09/04/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: 0.248015873015873,
            [TASK_TYPE]: 'P1-PM / DM / PC',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 22500,
            children: [],
          },
          {
            [TASK_NAME]: 'PC-LATAM-P1-3',
            [WBS_CODE_PPSA]: '2.1.4',
            [ROLE_NAME_PRICING_SHEET]: '(LATAM Project Coordinator-P1-3)',
            [ASSIGNED_TO]: '(LATAM - Project Coordinator - Consultant 13)',
            [BUDGETED_HOURS]: 225,
            [EFFORT_HRS]: 150,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 150,
            [DURATION]: '189d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '09/04/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: 0.0992063492063492,
            [TASK_TYPE]: 'P1-PM / DM / PC',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 9000,
            children: [],
          },
          {
            [TASK_NAME]: 'PC-LATAM-P1-4',
            [WBS_CODE_PPSA]: '2.1.5',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '(LATAM - Project Coordinator - Consultant 14)',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: 150,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 150,
            [DURATION]: '189d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '09/04/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: 0.0992063492063492,
            [TASK_TYPE]: 'P1-PM / DM / PC',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 9000,
            children: [],
          },
          {
            [TASK_NAME]: 'PE-USA-P1-4',
            [WBS_CODE_PPSA]: '2.1.6',
            [ROLE_NAME_PRICING_SHEET]: '(US Project Executive-P1-4)',
            [ASSIGNED_TO]: '(Project Executive - Advisory 14)',
            [BUDGETED_HOURS]: 50,
            [EFFORT_HRS]: 50,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 50,
            [DURATION]: '189d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '09/04/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: 0.0330687830687831,
            [TASK_TYPE]: 'P1-PM / DM / PC',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 3000,
            children: [],
          },
          {
            [TASK_NAME]: '1 - Employee Central',
            [WBS_CODE_PPSA]: '2.1.7',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '1d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '12/08/25',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: '2 - Employee Central Time / Time Off',
            [WBS_CODE_PPSA]: '2.1.8',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '23d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '01/09/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: '8 - Recruiting Management',
            [WBS_CODE_PPSA]: '2.1.9',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '33d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '01/26/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: '9 - Recruiting Marketing',
            [WBS_CODE_PPSA]: '2.1.10',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '33d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '01/26/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: '10 - Onboarding',
            [WBS_CODE_PPSA]: '2.1.11',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '33d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '01/26/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: '12 - Compensation Management',
            [WBS_CODE_PPSA]: '2.1.12',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: '',
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '37d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '01/30/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P1-1 - Employee Central',
        [WBS_CODE_PPSA]: '2.2',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 850,
        [EFFORT_HRS]: 850,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 1050,
        [DURATION]: '450d',
        [START_DATE]: '12/09/25',
        [END_DATE]: '09/20/27',
        [PREDECESSORS]: 22,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 1,
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 63000,
        children: [
          {
            [TASK_NAME]: 'Advanced data migration',
            [WBS_CODE_PPSA]: '2.2.1',
            [ROLE_NAME_PRICING_SHEET]:
              '(1-EC-Advanced data migration-Consultant-USA-P1-1)',
            [ASSIGNED_TO]:
              '(Employee Central - Consultant 11)\n(Employee Central - Lead 13)',
            [BUDGETED_HOURS]: 50,
            [EFFORT_HRS]: 50,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 50,
            [DURATION]: '450d',
            [START_DATE]: '12/09/25',
            [END_DATE]: '09/20/27',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.00694444444444445,
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 3000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.2.2',
            [ROLE_NAME_PRICING_SHEET]:
              '(1-EC-Core scope-Consultant-LATAM-P1-2)',
            [ASSIGNED_TO]: '(LATAM - Employee Central - Consultant 12)',
            [BUDGETED_HOURS]: 400,
            [EFFORT_HRS]: 100,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 100,
            [DURATION]: '149d',
            [START_DATE]: '12/09/25',
            [END_DATE]: '07/13/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.0838926174496644,
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 6000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.2.3',
            [ROLE_NAME_PRICING_SHEET]:
              '(1-EC-Core scope-Consultant-LATAM-P1-2)',
            [ASSIGNED_TO]: '(LATAM - Employee Central - 14)',
            [BUDGETED_HOURS]: 400,
            [EFFORT_HRS]: 400,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 400,
            [DURATION]: '149d',
            [START_DATE]: '12/09/25',
            [END_DATE]: '07/13/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.335570469798658,
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 24000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.2.4',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '(Employee Central - Advisory)',
            [BUDGETED_HOURS]: 0,
            [EFFORT_HRS]: 100,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 100,
            [DURATION]: '149d',
            [START_DATE]: '12/09/25',
            [END_DATE]: '07/13/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.0838926174496644,
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 6000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.2.5',
            [ROLE_NAME_PRICING_SHEET]: '(1-EC-Core scope-Lead-USA-P1-3)',
            [ASSIGNED_TO]: '(Employee Central - Lead 13)',
            [BUDGETED_HOURS]: 400,
            [EFFORT_HRS]: 400,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 400,
            [DURATION]: '149d',
            [START_DATE]: '12/09/25',
            [END_DATE]: '07/13/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.335570469798658,
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 24000,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P1-2 - Employee Central Time / Time Off',
        [WBS_CODE_PPSA]: '2.3',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 1050,
        [EFFORT_HRS]: 1050,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 1050,
        [DURATION]: '126d',
        [START_DATE]: '01/12/26',
        [END_DATE]: '07/10/26',
        [PREDECESSORS]: 23,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 2,
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 63000,
        children: [
          {
            [TASK_NAME]: 'Core scope Time Off',
            [WBS_CODE_PPSA]: '2.3.1',
            [ROLE_NAME_PRICING_SHEET]:
              '(2-EC Time / TM Off-Core scope Time Off-Consultant-LATAM-P1-1)',
            [ASSIGNED_TO]:
              '(LATAM - Employee Central Time Off - Consultant 11)',
            [BUDGETED_HOURS]: 100,
            [EFFORT_HRS]: 100,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 100,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.0992063492063492,
            [TASK_TYPE]: 'P1-Employee Central Time / Time Off',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 6000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope Time Off',
            [WBS_CODE_PPSA]: '2.3.2',
            [ROLE_NAME_PRICING_SHEET]:
              '(2-EC Time / TM Off-Core scope Time Off-Lead-USA-P1-2)',
            [ASSIGNED_TO]: '(Employee Central Time Off - Lead 12)',
            [BUDGETED_HOURS]: 150,
            [EFFORT_HRS]: 150,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 150,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.148809523809524,
            [TASK_TYPE]: 'P1-Employee Central Time / Time Off',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 9000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope Time Tracking -CA',
            [WBS_CODE_PPSA]: '2.3.3',
            [ROLE_NAME_PRICING_SHEET]:
              '(2-EC Time / TM Off-Core scope Time Tracking -CA-Consultant-USA-P1-3)',
            [ASSIGNED_TO]: '(Employee Central Time Off - Consultant 13)',
            [BUDGETED_HOURS]: 100,
            [EFFORT_HRS]: 100,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 100,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.0992063492063492,
            [TASK_TYPE]: 'P1-Employee Central Time / Time Off',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 6000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope Time Tracking -CA',
            [WBS_CODE_PPSA]: '2.3.4',
            [ROLE_NAME_PRICING_SHEET]:
              '(2-EC Time / TM Off-Core scope Time Tracking -CA-Lead-USA-P1-4)',
            [ASSIGNED_TO]: '(Employee Central Time Off - Lead 14)',
            [BUDGETED_HOURS]: 150,
            [EFFORT_HRS]: 150,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 150,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.148809523809524,
            [TASK_TYPE]: 'P1-Employee Central Time / Time Off',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 9000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope Time Tracking -USA',
            [WBS_CODE_PPSA]: '2.3.5',
            [ROLE_NAME_PRICING_SHEET]:
              '(2-EC Time / TM Off-Core scope Time Tracking -USA-Consultant-LATAM-P1-5)',
            [ASSIGNED_TO]:
              '(LATAM - Employee Central Time Off - Consultant 15)',
            [BUDGETED_HOURS]: 250,
            [EFFORT_HRS]: 250,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 250,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.248015873015873,
            [TASK_TYPE]: 'P1-Employee Central Time / Time Off',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 15000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope Time Tracking -USA',
            [WBS_CODE_PPSA]: '2.3.6',
            [ROLE_NAME_PRICING_SHEET]:
              '(2-EC Time / TM Off-Core scope Time Tracking -USA-Lead-USA-P1-6)',
            [ASSIGNED_TO]: '(Employee Central Time Off - Lead 16)',
            [BUDGETED_HOURS]: 300,
            [EFFORT_HRS]: 300,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 300,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.297619047619048,
            [TASK_TYPE]: 'P1-Employee Central Time / Time Off',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 18000,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P1-8 - Recruiting Management',
        [WBS_CODE_PPSA]: '2.4',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 500,
        [EFFORT_HRS]: 500,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 600,
        [DURATION]: '93d',
        [START_DATE]: '01/27/26',
        [END_DATE]: '06/05/26',
        [PREDECESSORS]: 24,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 8,
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 36000,
        children: [
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.4.1',
            [ROLE_NAME_PRICING_SHEET]:
              '(8-RCM-Core scope-Consultant-LATAM-P1-1)',
            [ASSIGNED_TO]: '(LATAM - Recruiting Management - Consultant 11)',
            [BUDGETED_HOURS]: 200,
            [EFFORT_HRS]: 200,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 200,
            [DURATION]: '93d',
            [START_DATE]: '01/27/26',
            [END_DATE]: '06/05/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.268817204301075,
            [TASK_TYPE]: 'P1-Recruiting Management',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 12000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.4.2',
            [ROLE_NAME_PRICING_SHEET]: '(8-RCM-Core scope-Lead-USA-P1-2)',
            [ASSIGNED_TO]: '(Recruiting Management - Lead 12)',
            [BUDGETED_HOURS]: 300,
            [EFFORT_HRS]: 400,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 400,
            [DURATION]: '93d',
            [START_DATE]: '01/27/26',
            [END_DATE]: '06/05/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.537634408602151,
            [TASK_TYPE]: 'P1-Recruiting Management',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 24000,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P1-9 - Recruiting Marketing',
        [WBS_CODE_PPSA]: '2.5',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 275,
        [EFFORT_HRS]: 275,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 275,
        [DURATION]: '93d',
        [START_DATE]: '01/27/26',
        [END_DATE]: '06/05/26',
        [PREDECESSORS]: 25,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 9,
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 16500,
        children: [
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.5.1',
            [ROLE_NAME_PRICING_SHEET]:
              '(9-RMK-Core scope-Consultant-LATAM-P1-1)',
            [ASSIGNED_TO]: '(LATAM - Recruiting Marketing - Consultant 11)',
            [BUDGETED_HOURS]: 100,
            [EFFORT_HRS]: 100,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 100,
            [DURATION]: '93d',
            [START_DATE]: '01/27/26',
            [END_DATE]: '06/05/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.134408602150538,
            [TASK_TYPE]: 'P1-Recruiting Marketing',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 6000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.5.2',
            [ROLE_NAME_PRICING_SHEET]: '(9-RMK-Core scope-Lead-USA-P1-2)',
            [ASSIGNED_TO]: '(Recruiting Marketing - Lead 12)',
            [BUDGETED_HOURS]: 175,
            [EFFORT_HRS]: 175,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 175,
            [DURATION]: '93d',
            [START_DATE]: '01/27/26',
            [END_DATE]: '06/05/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.235215053763441,
            [TASK_TYPE]: 'P1-Recruiting Marketing',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 10500,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P1-10 - Onboarding',
        [WBS_CODE_PPSA]: '2.6',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 400,
        [EFFORT_HRS]: 400,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 500,
        [DURATION]: '93d',
        [START_DATE]: '01/27/26',
        [END_DATE]: '06/05/26',
        [PREDECESSORS]: 26,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 10,
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 30000,
        children: [
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.6.1',
            [ROLE_NAME_PRICING_SHEET]:
              '(10-Onb-Core scope-Consultant-LATAM-P1-1)',
            [ASSIGNED_TO]: '(LATAM - Onboarding - Consultant 11)',
            [BUDGETED_HOURS]: 150,
            [EFFORT_HRS]: 150,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 150,
            [DURATION]: '93d',
            [START_DATE]: '01/27/26',
            [END_DATE]: '06/05/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.201612903225806,
            [TASK_TYPE]: 'P1-Onboarding',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 9000,
            children: [],
          },
          {
            [TASK_NAME]: 'Core scope',
            [WBS_CODE_PPSA]: '2.6.2',
            [ROLE_NAME_PRICING_SHEET]: '(10-Onb-Core scope-Lead-USA-P1-2)',
            [ASSIGNED_TO]: '(Onboarding - Lead 12)',
            [BUDGETED_HOURS]: 250,
            [EFFORT_HRS]: 350,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 350,
            [DURATION]: '93d',
            [START_DATE]: '01/27/26',
            [END_DATE]: '06/05/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.470430107526882,
            [TASK_TYPE]: 'P1-Onboarding',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 21000,
            children: [],
          },
        ],
      },
      {
        [TASK_NAME]: 'P1-12 - Compensation Management',
        [WBS_CODE_PPSA]: '2.7',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 1000,
        [EFFORT_HRS]: 1000,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 1000,
        [DURATION]: '40d',
        [START_DATE]: '02/02/26',
        [END_DATE]: '03/27/26',
        [PREDECESSORS]: 27,
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: 12,
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 60000,
        children: [
          {
            [TASK_NAME]: 'Comp Scope',
            [WBS_CODE_PPSA]: '2.7.1',
            [ROLE_NAME_PRICING_SHEET]: '(12-Comp-Comp Scope-Lead-USA-P1-1)',
            [ASSIGNED_TO]: '(Compensation Management - Lead 11)',
            [BUDGETED_HOURS]: 1000,
            [EFFORT_HRS]: 1000,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 1000,
            [DURATION]: '40d',
            [START_DATE]: '02/02/26',
            [END_DATE]: '03/27/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 3.125,
            [TASK_TYPE]: 'P1-Compensation Management',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 60000,
            children: [],
          },
        ],
      },
    ],
  },
  {
    [TASK_NAME]: 'Integrations (All Phases)',
    [WBS_CODE_PPSA]: '3',
    [ROLE_NAME_PRICING_SHEET]: '',
    [ASSIGNED_TO]: '',
    [BUDGETED_HOURS]: 460,
    [EFFORT_HRS]: 460,
    [WORKED_TASK_HOURS]: 0,
    [REMAINING_TASK_HOURS]: 460,
    [DURATION]: '154d',
    [START_DATE]: '12/08/25',
    [END_DATE]: '07/17/26',
    [PREDECESSORS]: '',
    [PERCENT_ALLOCATION]: '',
    [TASK_TYPE]: '',
    [COMMENTS]: '',
    [OPEN_FOR_TIME]: '',
    [WORKED_MINUTES_PPSA]: 0,
    [REMAINING_MINUTES_PPSA]: 27600,
    children: [
      {
        [TASK_NAME]: 'Integration Delivery',
        [WBS_CODE_PPSA]: '3.1',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 460,
        [EFFORT_HRS]: 460,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 460,
        [DURATION]: '154d',
        [START_DATE]: '12/08/25',
        [END_DATE]: '07/17/26',
        [PREDECESSORS]: '',
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: '',
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 27600,
        children: [
          {
            [TASK_NAME]: 'Phase 1 Start Leads (Day Minus 1)',
            [WBS_CODE_PPSA]: '3.1.1',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: 0,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '23d',
            [START_DATE]: '12/08/25',
            [END_DATE]: '01/09/26',
            [PREDECESSORS]: 16,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: 'Phase 1 Start Consultants (Day Minus 1)',
            [WBS_CODE_PPSA]: '3.1.2',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '',
            [BUDGETED_HOURS]: '',
            [EFFORT_HRS]: 0,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 0,
            [DURATION]: '1d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '01/12/26',
            [PREDECESSORS]: 54,
            [PERCENT_ALLOCATION]: '',
            [TASK_TYPE]: 'P1-Employee Central',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 0,
            children: [],
          },
          {
            [TASK_NAME]: '401k - (US Integration Lead 1-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.3',
            [ROLE_NAME_PRICING_SHEET]: '(US Integration Lead 1-P1)',
            [ASSIGNED_TO]: '(Integrations - SAP BTP - Lead 11)',
            [BUDGETED_HOURS]: 50,
            [EFFORT_HRS]: 50,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 50,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: 54,
            [PERCENT_ALLOCATION]: 0.0496031746031746,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 3000,
            children: [],
          },
          {
            [TASK_NAME]: '401k - (Labs Payroll Integration Lead 1-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.4',
            [ROLE_NAME_PRICING_SHEET]: '(Labs Payroll Integration Lead 1-P1)',
            [ASSIGNED_TO]: '(LABS - Integrations - SAP BTP - Advisory 11)',
            [BUDGETED_HOURS]: 30,
            [EFFORT_HRS]: 30,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 30,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: 54,
            [PERCENT_ALLOCATION]: 0.0297619047619048,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 1800,
            children: [],
          },
          {
            [TASK_NAME]: '401k - (Labs Integration Consultant 1-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.5',
            [ROLE_NAME_PRICING_SHEET]: '(Labs Integration Consultant 1-P1)',
            [ASSIGNED_TO]: '(LABS - Integrations - SAP BTP - Consultant 11)',
            [BUDGETED_HOURS]: 40,
            [EFFORT_HRS]: 40,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 40,
            [DURATION]: '130d',
            [START_DATE]: '01/13/26',
            [END_DATE]: '07/17/26',
            [PREDECESSORS]: 55,
            [PERCENT_ALLOCATION]: 0.0384615384615385,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 2400,
            children: [],
          },
          {
            [TASK_NAME]: 'AD - (US Integration Lead 1-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.6',
            [ROLE_NAME_PRICING_SHEET]: '(US Integration Lead 1-P1)',
            [ASSIGNED_TO]: '(Integrations - SAP BTP - Lead 11)',
            [BUDGETED_HOURS]: 60,
            [EFFORT_HRS]: 60,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 60,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: 54,
            [PERCENT_ALLOCATION]: 0.0595238095238095,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 3600,
            children: [],
          },
          {
            [TASK_NAME]: 'AD - (Labs Payroll Integration Lead 1-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.7',
            [ROLE_NAME_PRICING_SHEET]: '(Labs Payroll Integration Lead 1-P1)',
            [ASSIGNED_TO]: '(LABS - Integrations - SAP BTP - Advisory 11)',
            [BUDGETED_HOURS]: 40,
            [EFFORT_HRS]: 40,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 40,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: 54,
            [PERCENT_ALLOCATION]: 0.0396825396825397,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 2400,
            children: [],
          },
          {
            [TASK_NAME]: 'AD - (Labs Integration Consultant 2-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.8',
            [ROLE_NAME_PRICING_SHEET]: '(Labs Integration Consultant 2-P1)',
            [ASSIGNED_TO]: '(LABS - Integrations - SAP BTP - Consultant 12)',
            [BUDGETED_HOURS]: 50,
            [EFFORT_HRS]: 50,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 50,
            [DURATION]: '130d',
            [START_DATE]: '01/13/26',
            [END_DATE]: '07/17/26',
            [PREDECESSORS]: 55,
            [PERCENT_ALLOCATION]: 0.0480769230769231,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 3000,
            children: [],
          },
          {
            [TASK_NAME]: 'GL fINANCE posting - (US Integration Lead 2-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.9',
            [ROLE_NAME_PRICING_SHEET]: '(US Integration Lead 2-P1)',
            [ASSIGNED_TO]: '(Integrations - SAP BTP - Lead 12)',
            [BUDGETED_HOURS]: 80,
            [EFFORT_HRS]: 80,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 80,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: 54,
            [PERCENT_ALLOCATION]: 0.0793650793650794,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 4800,
            children: [],
          },
          {
            [TASK_NAME]:
              'GL fINANCE posting - (Labs Payroll Integration Lead 1-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.10',
            [ROLE_NAME_PRICING_SHEET]: '(Labs Payroll Integration Lead 1-P1)',
            [ASSIGNED_TO]: '(LABS - Integrations - SAP BTP - Advisory 11)',
            [BUDGETED_HOURS]: 50,
            [EFFORT_HRS]: 50,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 50,
            [DURATION]: '126d',
            [START_DATE]: '01/12/26',
            [END_DATE]: '07/10/26',
            [PREDECESSORS]: 54,
            [PERCENT_ALLOCATION]: 0.0496031746031746,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 3000,
            children: [],
          },
          {
            [TASK_NAME]:
              'GL fINANCE posting - (Labs Integration Consultant 3-P1) - P1',
            [WBS_CODE_PPSA]: '3.1.11',
            [ROLE_NAME_PRICING_SHEET]: '(Labs Integration Consultant 3-P1)',
            [ASSIGNED_TO]: '(LABS - Integrations - SAP BTP - Consultant 13)',
            [BUDGETED_HOURS]: 60,
            [EFFORT_HRS]: 60,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 60,
            [DURATION]: '130d',
            [START_DATE]: '01/13/26',
            [END_DATE]: '07/17/26',
            [PREDECESSORS]: 55,
            [PERCENT_ALLOCATION]: 0.0576923076923077,
            [TASK_TYPE]: 'P1-Integrations - BTP / Boomi',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 3600,
            children: [],
          },
        ],
      },
    ],
  },
  {
    [TASK_NAME]: 'Hypercare',
    [WBS_CODE_PPSA]: '4',
    [ROLE_NAME_PRICING_SHEET]: '',
    [ASSIGNED_TO]: '',
    [BUDGETED_HOURS]: 300,
    [EFFORT_HRS]: 300,
    [WORKED_TASK_HOURS]: 0,
    [REMAINING_TASK_HOURS]: 200,
    [DURATION]: '92d',
    [START_DATE]: '03/23/26',
    [END_DATE]: '07/31/26',
    [PREDECESSORS]: '',
    [PERCENT_ALLOCATION]: '',
    [TASK_TYPE]: '',
    [COMMENTS]: '',
    [OPEN_FOR_TIME]: '',
    [WORKED_MINUTES_PPSA]: 0,
    [REMAINING_MINUTES_PPSA]: 12000,
    children: [
      {
        [TASK_NAME]: 'P2-Hypercare',
        [WBS_CODE_PPSA]: '4.1',
        [ROLE_NAME_PRICING_SHEET]: '',
        [ASSIGNED_TO]: '',
        [BUDGETED_HOURS]: 300,
        [EFFORT_HRS]: 300,
        [WORKED_TASK_HOURS]: 0,
        [REMAINING_TASK_HOURS]: 200,
        [DURATION]: '92d',
        [START_DATE]: '03/23/26',
        [END_DATE]: '07/31/26',
        [PREDECESSORS]: '',
        [PERCENT_ALLOCATION]: '',
        [TASK_TYPE]: '',
        [COMMENTS]: '',
        [OPEN_FOR_TIME]: '',
        [WORKED_MINUTES_PPSA]: 0,
        [REMAINING_MINUTES_PPSA]: 12000,
        children: [
          {
            [TASK_NAME]: 'Hypercare',
            [WBS_CODE_PPSA]: '4.1.1',
            [ROLE_NAME_PRICING_SHEET]: '',
            [ASSIGNED_TO]: '(Hypercare - Lead)',
            [BUDGETED_HOURS]: 300,
            [EFFORT_HRS]: 200,
            [WORKED_TASK_HOURS]: 0,
            [REMAINING_TASK_HOURS]: 200,
            [DURATION]: '92d',
            [START_DATE]: '03/23/26',
            [END_DATE]: '07/31/26',
            [PREDECESSORS]: '',
            [PERCENT_ALLOCATION]: 0.271739130434783,
            [TASK_TYPE]: 'Hypercare',
            [COMMENTS]: '',
            [OPEN_FOR_TIME]: '',
            [WORKED_MINUTES_PPSA]: 0,
            [REMAINING_MINUTES_PPSA]: 12000,
            children: [],
          },
        ],
      },
    ],
  },
];
